[package]
name = "geo-test-fixtures"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
wkt = { version = "0.13", git = "https://github.com/TimTheBig/wkt.git", default-features = false }
geo-types = { path = "../geo-types" }
